### ISSUE TITLE
Choose the Voyage Project

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v27-bears-team-06#1]
**Feature Description**
Select the project this team will create during Voyage 27

**Major User Stories/Tasks**
- [x] Create Vision Statement
- [x] Define & prioritize application features
- [x] Identify feature required for the Minimum Viable Product (MVP)
- [x] Create Product Backlog

**Additional Considerations**
Include anything else that may be helpful. For example, links to external resources.
