### ISSUE TITLE
Identify the name of a bird from its picture

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v27-bears-team-06#14]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [x] User can send URL of the image of a bird to be recognized
- [x] User can see the image from the URL they’ve supplied
- [x] User can see whether the bird is recognized or not and it’s name 
- [ ] User can reset the input fields to make a new request
- [ ] App must be responsive (mobile friendly)

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
