### ISSUE TITLE
Provide information customized to the specific End User

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v27-bears-team-06#26]
**__Feature Description__**
Provide information customized to the specific End User

**__Major User Stories/tasks__**
- [ ] Add user login capability
- [ ] User can see additional data about a bird based on where the user is located. For example,  the likelyhood that bird is to be found in the users location
- [ ] User can create/update bird history based on her application use history
- [ ] User can display charts to see how common a bird that has just been identified is to the users region 

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
