### ISSUE TITLE
Non-critical Use & Usability Enhancements

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v27-bears-team-06#31]
**__Feature Description__**
Describe what the feature is intended to accomplish & why it's important

**__Major User Stories/tasks__**
- [ ] User can retrieve details on bird via an open source reference (Wikipedia?)
- [ ] Allow user to upload image from Dropbox, Google Drive, or other popular host
- [ ] User can send audio recording in form and retrieve bird data from it
- [ ] User can use mobile camera for direct image input
- [ ] User can see global map of other users found birds (pulled from our db)
- [ ] User can upload a video URL rather than the URL of a static image

**__Additional Considerations__**
N/a
