### ISSUE TITLE
Define the Team Workflow

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v27-bears-team-06#7]
**__Feature Description__**
Define the team workflow including git branch names, PR rules, etc.

**__Major User Stories/tasks__**
- [x] Define git branches & naming conventions
- [x] Set up default branch & branch protection rules
- [x] Conduct Git Workflow overview for the team

**__Additional Considerations__**
N/a
